import '../../features/auth/models/user_model.dart';
import '../../features/documents/models/document_model.dart';
import '../../features/secure_sharing/models/share_model.dart';
import '../../features/notifications/models/notification_model.dart';
import '../../features/partner_api/models/partner_api_model.dart';

class DemoDataService {
  static UserModel get initialUser => UserModel(
    id: 'USR-893201',
    fullName: 'Grishma Thakare',
    gender: 'Male',
    dob: '21/11/2005',
    mobileNumber: '+91 98765 43210',
    email: 'grishma.thakare@itm.edu.in',
    aadhaarLast4: '9812',
    isBiometricEnabled: true,
    isPinSet: true,
    securityPin: '1234',
    isPremium: false,
    usedStorageMb: 142.5,
    totalStorageMb: 1024.0, // 1 GB free
  );

  static List<DocumentModel> get initialDocuments => [
    DocumentModel(
      id: 'DOC-AADHAAR-01',
      title: 'Aadhaar Identity Card',
      category: 'Identity',
      issuerName: 'UIDAI - Unique Identification Authority of India',
      issuerLogoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Aadhaar_Logo.svg/1200px-Aadhaar_Logo.svg.png',
      rawDocumentNumber: '981245679812',
      maskedDocumentNumber: 'XXXX-XXXX-9812',
      holderName: 'Grishma Thakare',
      issueDate: '15 Jan 2018',
      expiryDate: 'Permanent',
      status: 'VERIFIED',
      checksum: 'e3b0c44298fc1c149afbf4c8996fb924',
      isFavorite: true,
      fileSizeMb: 1.4,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-AADHAAR-01|UIDAI|Grishma Thakare|e3b0c44298fc1c149afbf4c8996fb924',
      digitalSignatureInfo: {
        'signerName': 'UIDAI Sub-CA Certificate Authority (Government of India)',
        'certificateId': 'X509-UIDAI-2024-9081',
        'algorithm': 'RSA 2048-bit / SHA-256 Digest',
        'sha256Fingerprint': '8F:3A:91:DE:45:B2:10:8C:77:E1:59:AA:02:44:99:BC:11:33:55:77',
        'timestamp': '2024-01-15T10:30:00Z',
        'tsaName': 'National Informatics Centre (NIC) TSA',
        'status': 'Valid Digital Signature',
      },
    ),
    DocumentModel(
      id: 'DOC-PAN-02',
      title: 'PAN Card (Permanent Account Number)',
      category: 'Identity',
      issuerName: 'Income Tax Department, Govt. of India',
      issuerLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Income_Tax_Department_Logo.png/800px-Income_Tax_Department_Logo.png',
      rawDocumentNumber: 'ABCPS9812F',
      maskedDocumentNumber: 'AB••••••12F',
      holderName: 'Grishma Thakare',
      issueDate: '10 Mar 2021',
      expiryDate: 'Permanent',
      status: 'VERIFIED',
      checksum: '4a8a08f09d37b73795649038408b5f33',
      isFavorite: true,
      fileSizeMb: 0.9,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-PAN-02|Income Tax Dept|Grishma Thakare|4a8a08f09d37b73795649038408b5f33',
      digitalSignatureInfo: {
        'signerName': 'Income Tax Dept e-Sign Root Authority',
        'certificateId': 'X509-ITD-2021-3321',
        'algorithm': 'ECDSA secp256r1 / SHA-256',
        'sha256Fingerprint': '32:99:AA:BB:CC:DD:EE:FF:11:22:33:44:55:66:77:88:99:00:11:22',
        'timestamp': '2021-03-10T14:15:22Z',
        'tsaName': 'CDAC e-Sign TSA Authority',
        'status': 'Valid Digital Signature',
      },
    ),
    DocumentModel(
      id: 'DOC-DL-03',
      title: 'Driving Licence',
      category: 'Transport',
      issuerName: 'Ministry of Road Transport & Highways (MoRTH)',
      issuerLogoUrl: 'https://morth.nic.in/sites/default/files/logo.png',
      rawDocumentNumber: 'MH02 20220098123',
      maskedDocumentNumber: 'MH02 2022••••123',
      holderName: 'Grishma Thakare',
      issueDate: '05 Aug 2022',
      expiryDate: '04 Aug 2042',
      status: 'VERIFIED',
      checksum: '9f86d081884c7d659a2feaa0c55ad015',
      isFavorite: false,
      fileSizeMb: 1.8,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-DL-03|MoRTH|Grishma Thakare|9f86d081884c7d659a2feaa0c55ad015',
      digitalSignatureInfo: {
        'signerName': 'State Transport Authority Certificate Root',
        'certificateId': 'X509-STA-MH-2022-8811',
        'algorithm': 'RSA 2048-bit / SHA-256',
        'sha256Fingerprint': '12:34:56:78:90:AB:CD:EF:FE:DC:BA:09:87:65:43:21:11:22:33:44',
        'timestamp': '2022-08-05T09:00:00Z',
        'tsaName': 'National Informatics Centre TSA',
        'status': 'Valid Digital Signature',
      },
    ),
    DocumentModel(
      id: 'DOC-CBSE-04',
      title: 'Class XII Senior School Certificate',
      category: 'Academic',
      issuerName: 'Central Board of Secondary Education (CBSE)',
      issuerLogoUrl: 'https://cbse.gov.in/images/cbse_logo.png',
      rawDocumentNumber: 'CBSE/2022/9812401',
      maskedDocumentNumber: 'CBSE/2022/••••401',
      holderName: 'Grishma Thakare',
      issueDate: '25 May 2022',
      expiryDate: 'Permanent',
      status: 'VERIFIED',
      checksum: '6b86b273ff34fce19d6b804eff5a3f57',
      isFavorite: true,
      fileSizeMb: 2.1,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-CBSE-04|CBSE|Grishma Thakare|6b86b273ff34fce19d6b804eff5a3f57',
      digitalSignatureInfo: {
        'signerName': 'CBSE Examination Controller Cryptographic Signer',
        'certificateId': 'X509-CBSE-2022-1002',
        'algorithm': 'RSA 2048-bit / SHA-256',
        'sha256Fingerprint': '77:88:99:00:11:22:33:44:55:66:77:88:99:00:AA:BB:CC:DD:EE:FF',
        'timestamp': '2022-05-25T11:45:00Z',
        'tsaName': 'DigiLocker Academic Repository TSA',
        'status': 'Valid Digital Signature',
      },
    ),
    DocumentModel(
      id: 'DOC-DEGREE-05',
      title: 'B.Tech Computer Science Degree Certificate',
      category: 'Academic',
      issuerName: 'ITM Skills University',
      issuerLogoUrl: 'https://www.itmuniversity.org/images/logo.png',
      rawDocumentNumber: 'ITMSU/2026/CSE/089',
      maskedDocumentNumber: 'ITMSU/2026/CSE/••••',
      holderName: 'Grishma Thakare',
      issueDate: '15 May 2026',
      expiryDate: 'Permanent',
      status: 'VERIFIED',
      checksum: 'd41d8cd98f00b204e9800998ecf8427e',
      isFavorite: false,
      fileSizeMb: 3.2,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-DEGREE-05|ITM Skills University|Grishma Thakare|d41d8cd98f00b204e9800998ecf8427e',
      digitalSignatureInfo: {
        'signerName': 'ITM Skills University Registrar Certificate Authority',
        'certificateId': 'X509-ITM-2026-0042',
        'algorithm': 'RSA 2048-bit / SHA-256',
        'sha256Fingerprint': 'AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99:12:34:56:78',
        'timestamp': '2026-05-15T16:00:00Z',
        'tsaName': 'National Academic Depository (NAD) TSA',
        'status': 'Valid Digital Signature',
      },
    ),
    DocumentModel(
      id: 'DOC-RC-06',
      title: 'Vehicle Registration Certificate (RC)',
      category: 'Transport',
      issuerName: 'State Transport Department, Maharashtra',
      issuerLogoUrl: 'https://parivahan.gov.in/parivahan/sites/all/themes/parivahan/logo.png',
      rawDocumentNumber: 'MH02EF9812',
      maskedDocumentNumber: 'MH02••••12',
      holderName: 'Grishma Thakare',
      issueDate: '12 Sep 2023',
      expiryDate: '11 Sep 2038',
      status: 'EXPIRING SOON',
      checksum: '098f6bcd4621d373cade4e832627b4f6',
      isFavorite: false,
      fileSizeMb: 1.1,
      fileType: 'PDF',
      qrPayload: 'DIGIVAULT:DOC-RC-06|Parivahan|Grishma Thakare|098f6bcd4621d373cade4e832627b4f6',
      digitalSignatureInfo: {
        'signerName': 'Parivahan e-Services Digital Signer',
        'certificateId': 'X509-RC-MH-2023-4412',
        'algorithm': 'ECDSA secp256r1',
        'sha256Fingerprint': '55:66:77:88:99:00:11:22:33:44:55:66:77:88:99:00:AA:BB:CC:DD',
        'timestamp': '2023-09-12T12:00:00Z',
        'tsaName': 'NIC Transport Portal TSA',
        'status': 'Valid Digital Signature',
      },
    ),
  ];

  static List<Map<String, String>> get popularIssuers => [
    {
      'name': 'UIDAI (Aadhaar)',
      'category': 'Central Government',
      'description': 'Unique Identification Authority of India',
      'code': 'UIDAI',
    },
    {
      'name': 'Income Tax Department',
      'category': 'Central Government',
      'description': 'PAN Card & Tax Assessment Orders',
      'code': 'ITD',
    },
    {
      'name': 'Ministry of Road Transport & Highways',
      'category': 'Transport',
      'description': 'Driving Licence, RC Book, Vehicle Fitness',
      'code': 'MORTH',
    },
    {
      'name': 'Central Board of Secondary Education (CBSE)',
      'category': 'Education',
      'description': 'Class X & XII Marksheets & Passing Certificates',
      'code': 'CBSE',
    },
    {
      'name': 'ITM Skills University',
      'category': 'Education',
      'description': 'B.Tech Degrees, Transcripts & Diplomas',
      'code': 'ITM',
    },
    {
      'name': 'National Health Authority',
      'category': 'Health',
      'description': 'ABHA Health ID & Vaccination Records',
      'code': 'NHA',
    },
  ];

  static List<ShareModel> get initialShares => [
    ShareModel(
      id: 'SHARE-01',
      documentId: 'DOC-AADHAAR-01',
      documentTitle: 'Aadhaar Identity Card',
      issuerName: 'UIDAI',
      shareToken: 'DV-AADHAAR-8901',
      recipientLabel: 'HDFC Bank KYC Verification',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      expiresAt: DateTime.now().add(const Duration(hours: 20)),
      accessCount: 2,
      maxAccessLimit: 5,
      allowDownload: false,
      enforceWatermark: true,
      isPasswordProtected: true,
      accessPin: '4321',
      status: 'ACTIVE',
    ),
    ShareModel(
      id: 'SHARE-02',
      documentId: 'DOC-DEGREE-05',
      documentTitle: 'B.Tech Computer Science Degree Certificate',
      issuerName: 'ITM Skills University',
      shareToken: 'DV-DEGREE-4412',
      recipientLabel: 'TCS Campus Placement Drive HR',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      expiresAt: DateTime.now().add(const Duration(days: 5)),
      accessCount: 4,
      maxAccessLimit: 10,
      allowDownload: true,
      enforceWatermark: true,
      isPasswordProtected: false,
      accessPin: '',
      status: 'ACTIVE',
    ),
  ];

  static List<NotificationModel> get initialNotifications => [
    NotificationModel(
      id: 'NOTIF-01',
      title: 'Cryptographic Backup Complete',
      message: 'Your hardware vault credentials were backed up using zero-knowledge encryption.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
      type: 'SECURITY',
      isRead: false,
    ),
    NotificationModel(
      id: 'NOTIF-02',
      title: 'Share Link Accessed',
      message: 'HDFC Bank KYC Verification opened your shared Aadhaar Card link.',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      type: 'SECURITY',
      isRead: false,
    ),
    NotificationModel(
      id: 'NOTIF-03',
      title: 'Document Sync Successful',
      message: 'ITM Skills University issued B.Tech Degree Certificate to Grishma Thakare\'s vault.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      type: 'ISSUER',
      isRead: true,
    ),
  ];

  static List<PartnerApiModel> get initialPartnerApis => [
    PartnerApiModel(
      id: 'PARTNER-01',
      partnerName: 'HDFC Bank Verification Portal',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/HDFC_Bank_Logo.svg/1200px-HDFC_Bank_Logo.svg.png',
      purpose: 'Digital KYC Verification for Account Opening',
      grantedPermissions: 'Read Identity (Aadhaar, PAN)',
      authorizedAt: DateTime.now().subtract(const Duration(days: 10)),
      expiresAt: DateTime.now().add(const Duration(days: 20)),
      isApproved: true,
      totalRequestsHandled: 3,
    ),
    PartnerApiModel(
      id: 'PARTNER-02',
      partnerName: 'TCS Campus Recruitment System',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/1200px-Tata_Consultancy_Services_Logo.svg.png',
      purpose: 'Academic Qualification Verification',
      grantedPermissions: 'Read Academic Certificates (Degree, Marksheet)',
      authorizedAt: DateTime.now().subtract(const Duration(days: 5)),
      expiresAt: DateTime.now().add(const Duration(days: 25)),
      isApproved: true,
      totalRequestsHandled: 1,
    ),
  ];
}
